locustfile = ./scenarios/http/gateway/existing_user_get_operations/scenario.py
spawn-rate = 1
run-time = 1m
headless = true
users = 5
html = ./scenarios/http/gateway/existing_user_get_operations/report.html